version: "3.2"

services:
  dev:
    container_name: amax-eva-testnet
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /opt/testnet/amax.eva.chain
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/opt/testnet/amax.eva.chain/.cargo
    volumes:
      - .:/opt/testnet/amax.eva.chain
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/amax-eva --dev --ws-external"
