version: "3.2"

services:
  amaxeva:
    container_name: "amax-eva-${NET}"
    image: "$EVA_IMG_TAG"
    working_dir: "/opt/amax.eva.chain"
    ports:
      - "9944:9944"
    env_file:
        - .env
    environment:
      - CARGO_HOME="/opt/${NET}/.cargo"
    volumes:
      - "$RUN_SHARE:/root/.local"
    networks:
      - internet
    command: "--${RUN_MODE} --ws-external"

networks:
  network-a:
  internet: