version: "3.2"

services:
  amaxeva:
    container_name: "amax-eva-${NET}"
    image: "$EVA_IMG_TAG"
    working_dir: "/opt/amax.eva.chain"
    ports:
      - "$P2P_PORT:19992"
      - "$HTTP_PORT:19993"
      - "$WS_PORT:19994"
    env_file:
        - ~/.amax_eva_$NET/eva.env
    environment:
      - CARGO_HOME="/opt/amax.eva.chain/.cargo"
    volumes:
      - "$DATA_SHARE:/opt/amax.eva.chain/data"
    networks:
      - internet
    command: "--chain=$CHAIN --keystore-path=./data/.validator $ARG_VALIDATOR $ARG_RPC_METHODS $ARG_WS $ARG_BOOTNODES"

networks:
  network-a:
  internet: