version: "3.2"

services:
  amaxeva:
    image: "$IMGTAG"
    container_name: eva_${NET}_${TAG}
    working_dir: /opt/amax.eva.chain
    ports:
      - "$P2P_PORT:19992"
      - "$HTTP_PORT:19993"
      - "$WS_PORT:19994"
    env_file:
      - ~/.amax_eva/$NET/${TAG}.env
    environment:
      - CARGO_HOME="/opt/amax.eva.chain/.cargo"
    volumes:
      - "$EVA_SHARE:/opt/amax.eva.chain"
    networks:
      - internet
    command: "--chain=$CHAIN -d /opt/amax.eva.chain --keystore-path=.validator $ARG_VALIDATOR $ARG_RPC_METHODS $ARG_WS $ARG_BOOTNODES"

networks:
  network-a:
  internet: