version: "3.2"

services:
  amaxeva:
    image: "$IMGTAG"
    user: root
    container_name: eva_${NET}_${TAG}
    working_dir: /opt/amax.eva.chain
    command: "--chain=$CHAIN -d . --keystore-path=$TAG $ARG_VALIDATOR $ARG_RPC $ARG_WS $NODEKEY_FILE $ARG_BOOTNODES"
    ports:
      - "$P2P_PORT:19992"
      - "$HTTP_PORT:19993"
      - "$WS_PORT:19994"
    volumes:
      - "$EVA_SHARE/chains:/opt/amax.eva.chain/chains"
      - "~/.amax_eva/$NET/$TAG:/opt/amax.eva.chain/$TAG"
networks:
  default:
    name: amax
    external: true