version: "3.2"

services:
  amaxeva:
    image: "$IMGTAG"
    container_name: eva_${NET}_${TAG}
    working_dir: /opt/amax.eva.chain
    entrypoint: ["./amax-eva", "--chain=$CHAIN -d .", "--keystore-path=$TAG $ARG_VALIDATOR", "$ARG_RPC_METHODS", "$ARG_WS", "$ARG_BOOTNODES"]
    ports:
      - "$P2P_PORT:19992"
      - "$HTTP_PORT:19993"
      - "$WS_PORT:19994"
    environment:
      - CARGO_HOME="/opt/amax.eva.chain/.cargo"
    volumes:
      - "$EVA_SHARE:/opt/amax.eva.chain"
      - "$EVA_SHARE/chains:/opt/amax.eva.chain/chains"
    networks:
      - internet
networks:
  network-a:
  internet: